/// <reference types="node" />
/**
 * Inlines the Emotion Hunter web game into one string the app's WebView loads
 * offline: every file in images/ becomes `window.NVC_IMAGES[id]`, every
 * `url(fonts/…)` a data URI. The output is committed because cloud EAS builds
 * cannot see the website repo.
 *
 *   bun run sync:game
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { extname, join, parse, resolve } from 'node:path';

const SOURCE = resolve(import.meta.dirname, '../../website/public/games/duygu-avcisi');
const OUTPUT = resolve(
  import.meta.dirname,
  '../src/features/games/duygu-avcisi/game-html.generated.ts',
);

const MIME: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
  '.ttf': 'font/ttf',
  '.otf': 'font/otf',
};

function fail(message: string): never {
  console.error(`sync-duygu-avcisi: ${message}`);
  process.exit(1);
}

function dataUri(file: string): string {
  const mime = MIME[extname(file).toLowerCase()];
  if (!mime) fail(`no MIME type for ${file}`);
  return `data:${mime};base64,${readFileSync(file).toString('base64')}`;
}

const indexFile = join(SOURCE, 'index.html');
if (!existsSync(indexFile)) fail(`missing ${indexFile}`);
let html = readFileSync(indexFile, 'utf8');

// The app injects its NVC_EMBED config right after <head>.
if (!/<head[^>]*>/i.test(html)) fail('index.html has no <head> tag');

// Fonts: url(fonts/x.woff2), quoted or not.
html = html.replace(/url\(\s*(['"]?)fonts\/([^'")]+)\1\s*\)/g, (_match, _quote, name: string) => {
  const file = join(SOURCE, 'fonts', name);
  if (!existsSync(file)) fail(`font not found: fonts/${name}`);
  return `url(${dataUri(file)})`;
});
if (/url\(\s*['"]?fonts\//.test(html)) fail('unresolved fonts/ url left in index.html');

// Images: one NVC_IMAGES entry per file, keyed by file name without extension.
const imagesDir = join(SOURCE, 'images');
const images: Record<string, string> = {};
for (const name of existsSync(imagesDir) ? readdirSync(imagesDir).sort() : []) {
  if (name.startsWith('.')) continue;
  images[parse(name).name] = dataUri(join(imagesDir, name));
}

const firstScript = html.search(/<script\b/i);
if (firstScript === -1) fail('index.html has no <script> tag');
html =
  html.slice(0, firstScript) +
  `<script>window.NVC_IMAGES=${JSON.stringify(images)};</script>\n` +
  html.slice(firstScript);

writeFileSync(
  OUTPUT,
  '// generated by scripts/sync-duygu-avcisi.ts, do not edit\n' +
    `export const GAME_HTML = ${JSON.stringify(html)};\n`,
);
console.log(
  `sync-duygu-avcisi: ${Object.keys(images).length} images, ${(html.length / 1024).toFixed(0)} KB → ${OUTPUT}`,
);
